### ISSUE TITLE
Add to nupic-community repo

### ISSUE THREAD

**Issue by passiweinberger** [nupic-community/sanity-nupic#9]
I think this would make it easier to find :)

**Comment by mrcslws** [comment]
Good point. I'm hoping to have a clearer picture of the future after this weekend.

Ultimately I'd like to see the experience of running an HTM have something like this, essentially by default, probably through boilerplate code, similar to matplotlib's placement in nupic today. I think **that** would make this easier to find :)

**Comment by mrcslws** [comment]
Fixed :)

**Comment by passiweinberger** [comment]
👍
